### ISSUE TITLE
Add a project tracker file to list all upstream dependencies of EKS Anywhere

### ISSUE THREAD

**Issue by abhay-krishna** [aws/eks-anywhere-build-tooling#115]
**What would you like to be added**:

A file that will list the upstream Github projects that are built from this repo. A possible format is
```YAML
projects:
- org: jetstack
  repos:
  - name: certmanager
- org: fluxcd
  repos:
  - name: flux2
  - name: helm-controller
  - name: kustomize-controller
  - name: notification-controller
  - name: source-controller
- org: kubernetes-sigs
   repos:
   - name: cluster-api
   - name: cluster-api-provider-aws
...
```

**Why is this needed**:

An inventory of the projects will provide a centralized view of all the upstream dependencies of EKS Anywhere. This can be thought of as an abstraction of a Software Bill of Materials.
