### ISSUE TITLE
Update Flux projects versions to latest upstream

### ISSUE THREAD

**Issue by abhay-krishna** [aws/eks-anywhere-build-tooling#340]
We need to upgrade the main Flux project and the Flux controllers to the following versions.
```YAML
fluxcd/flux2: v0.25.1
fluxcd/helm-controller: v0.15.0
fluxcd/kustomize-controller: v0.19.0
fluxcd/notification-controller: v0.20.1
fluxcd/source-controller: v0.20.1
```
